import Sidebar from './components/Sidebar'
import './globals.css'
import { Quicksand } from 'next/font/google'

const inter = Quicksand({ subsets: ['latin'],  weight: ['500']})

export const metadata = {
  title: 'Thrillers travels UI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='flex'>
        <Sidebar />
        {children}
        </main>
      </body>
    </html>
  )
}
